# Generated by Django 2.1.4 on 2019-01-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, help_text='Address you have to ship this product to', max_length=500),
        ),
    ]
