# Generated by Django 2.1.4 on 2019-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the customer', max_length=254, null=True),
        ),
    ]
